fix: jest for do-component
digitalorigin/create-react-app pull request #6
Opened 2018-01-23 16:39 UTC by marduke182

In order to test packages using do-components we must no ignore this modules in jest babel parser

![](https://media.giphy.com/media/l41JT45p6ndCSmxAk/giphy.gif)

2018-01-25 10:48 UTC, sergi-io approved these changes

2018-01-25 11:16 UTC, marchys approved these changes

2018-01-25 15:45 UTC, martapower approved these changes

2018-01-26 08:42 UTC, catalanska requested changes
no gif

2018-01-26 08:54 UTC, marduke182 commented
@catalanska it has a gif but github is not working... if you edit the PR's you can see the gif there

2018-01-26 09:00 UTC, catalanska commented
fixed the gif issue

2018-01-26 09:00 UTC, catalanska approved these changes

2018-01-31 10:51 UTC, sergi-io approved these changes

2018-07-14 07:44 UTC, closed without merging